[client]
remote_addr = "localhost:2333"
default_token = "123"

[client.services.iperf3-udp]
type = "udp"
local_addr = "127.0.0.1:80"

[client.services.iperf3-tcp]
type = "tcp"
local_addr = "127.0.0.1:80"
