[server]
bind_addr = "0.0.0.0:2333"
default_token = "123"

[server.transport]
type = "tls"
[server.transport.tls]
pkcs12 = "examples/tls/identity.pfx"
pkcs12_password = "1234"

[server.services.foo1]
bind_addr = "0.0.0.0:5202"
