[client]
remote_addr = "localhost:2333"
default_token = "123"

[client.transport]
type = "noise"
[client.transport.noise]
remote_public_key = "xrpknQcAagcd/b9foMwxSCD+EindWxq450NEONk8XQo="

[client.services.foo1]
local_addr = "127.0.0.1:80"
