[server]
bind_addr = "0.0.0.0:2333"
default_token = "123"

[server.transport]
type = "noise"
[server.transport.noise]
local_private_key = "QLYMByBnjgM254zT6YKaBVvuAA61swyZfFxoA/SKZHM="

[server.services.foo1]
bind_addr = "0.0.0.0:5202"
